workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    scripts:
      - name: Update Podfile for Flutter
        script: |
          echo "Updating Podfile..."
          cd ios
          echo "platform :ios, '15.0'" > Podfile.tmp
          cat Podfile >> Podfile.tmp
          mv Podfile.tmp Podfile
          # Add configuration for flutter_secure_storage
          sed -i '' 's/post_install do |installer|/post_install do |installer|\n  installer.pods_project.targets.each do |target|\n    if target.name == "flutter_secure_storage"\n      target.build_configurations.each do |config|\n        config.build_settings["SWIFT_VERSION"] = "5.0"\n        config.build_settings["ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES"] = "YES"\n      end\n    end\n  end/g' Podfile
      - name: Update iPhone-only configuration
        script: |
          echo "Configuring for iPhone only..."
          cd ios
          # Update Info.plist
          /usr/libexec/PlistBuddy -c "Delete :UISupportedInterfaceOrientations~ipad" Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :UIDeviceFamily array" Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :UIDeviceFamily:0 integer 1" Runner/Info.plist || true
          # Update project.pbxproj
          sed -i '' 's/TARGETED_DEVICE_FAMILY = "1,2";/TARGETED_DEVICE_FAMILY = 1;/g' Runner.xcodeproj/project.pbxproj
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Flutter build iOS
        script: |
          flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.app.dSYM.zip
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - oneappsmj@gmail.com
