workflows:
  ios-method-1:
    name: IOS signing method-1 workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.downloadsplatform.CV8N38BFPJ
    scripts:
      - script: keychain initialize
      - script: keychain add-certificates
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: flutter build ipa and automatic versioning
        script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - oneappsmj@gmail.com

  ios-method-2:
    name: ios signing method-2 workflow
    environment:
      ios_signing:
        provisioning_profiles:
          - com.example.downloadsplatform.CV8N38BFPJ
        certificates:
          - Download_Platform
    scripts:
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - oneappsmj@gmail.com
