// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwe4nsl7sw7UQhJrblR1F43AwHdnkU8qQ',
    appId: '1:714082612352:web:2fa1f4277fbb44a5eda265',
    messagingSenderId: '714082612352',
    projectId: 'downloader-874df',
    authDomain: 'downloader-874df.firebaseapp.com',
    storageBucket: 'downloader-874df.firebasestorage.app',
    measurementId: 'G-465DCLQB0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwmurnHePjX5dzB8uYdTy1P8PZLuY0hc',
    appId: '1:714082612352:android:3fdf1bd1f343d71aeda265',
    messagingSenderId: '714082612352',
    projectId: 'downloader-874df',
    storageBucket: 'downloader-874df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xFfQC7PwTPLMXhvWoLx6EMvezrV7iKk',
    appId: '1:714082612352:ios:332184446b6600a6eda265',
    messagingSenderId: '714082612352',
    projectId: 'downloader-874df',
    storageBucket: 'downloader-874df.firebasestorage.app',
    androidClientId: '714082612352-2v3a4gb0taohvdk45pmr2kb3ckq8t6v4.apps.googleusercontent.com',
    iosClientId: '714082612352-picqfu8ddmo2i5icqqlrai0fptv1lotg.apps.googleusercontent.com',
    iosBundleId: 'com.example.downloadsplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xFfQC7PwTPLMXhvWoLx6EMvezrV7iKk',
    appId: '1:714082612352:ios:332184446b6600a6eda265',
    messagingSenderId: '714082612352',
    projectId: 'downloader-874df',
    storageBucket: 'downloader-874df.firebasestorage.app',
    androidClientId: '714082612352-2v3a4gb0taohvdk45pmr2kb3ckq8t6v4.apps.googleusercontent.com',
    iosClientId: '714082612352-picqfu8ddmo2i5icqqlrai0fptv1lotg.apps.googleusercontent.com',
    iosBundleId: 'com.example.downloadsplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwe4nsl7sw7UQhJrblR1F43AwHdnkU8qQ',
    appId: '1:714082612352:web:2fa1f4277fbb44a5eda265',
    messagingSenderId: '714082612352',
    projectId: 'downloader-874df',
    authDomain: 'downloader-874df.firebaseapp.com',
    storageBucket: 'downloader-874df.firebasestorage.app',
    measurementId: 'G-465DCLQB0L',
  );

}