name: Flutter CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"

      - name: Display Flutter/Dart version
        run: |
          flutter --version
          dart --version

      - name: Get dependencies
        run: flutter pub get

      - name: Fix plugin issues
        run: |
          echo "Running plugin fixes"
          # Simplified fix script to avoid complex heredocs
          mkdir -p "$HOME/.pub-cache/hosted/pub.dev/video_thumbnail-0.5.3/android/"
          mkdir -p "$HOME/.pub-cache/hosted/pub.dev/image_gallery_saver-2.0.3/android/"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Pod repo update
        run: pod repo update

      - name: Create all plugin privacy bundles (pre-install)
        run: |
          # Define arrays
          PLUGINS=(
            "video_player_avfoundation"
            "url_launcher_ios"
            "sqflite_darwin"
            "share_plus"
            "shared_preferences_foundation"
            "path_provider_foundation"
            "flutter_secure_storage"
            "screen_brightness_ios"
            "pointer_interceptor_ios"
            # Add any potential Flutter plugins that might need privacy bundles
            "flutter_local_notifications"
            "image_picker_ios"
            "camera_avfoundation"
            "google_maps_flutter_ios"
            "file_picker"
            "flutter_native_splash"
            "flutter_inappwebview"
            "device_info_plus"
            "connectivity_plus"
            "firebase_messaging"
            "firebase_core"
            "firebase_analytics"
          )

          CONFIGS=(
            "Debug-iphoneos"
            "Release-iphoneos"
            "Debug-iphonesimulator"
            "Release-iphonesimulator"
          )

          BASE_DIRS=(
            "build/ios"
            "ios/Flutter"
            "build/ios/iphoneos"
            "ios/build"
            "build"
            "ios"
            ".symlinks/plugins"
          )

          echo "Creating privacy bundles for all plugins..."

          # Create comprehensive set of bundles for all plugins
          for plugin in "${PLUGINS[@]}"; do
            # Log the plugin being processed
            echo "Processing privacy bundles for plugin: ${plugin}"
            
            # Create in all build configurations
            for config in "${CONFIGS[@]}"; do
              for base_dir in "${BASE_DIRS[@]}"; do
                mkdir -p "${base_dir}/${config}/${plugin}/${plugin}_privacy.bundle"
                touch "${base_dir}/${config}/${plugin}/${plugin}_privacy.bundle/${plugin}_privacy"
                touch "${base_dir}/${config}/${plugin}/${plugin}_privacy.bundle/PrivacyInfo.xcprivacy"
                
                # Also create in a common location that might be referenced
                mkdir -p "${base_dir}/${plugin}/${plugin}_privacy.bundle"
                touch "${base_dir}/${plugin}/${plugin}_privacy.bundle/${plugin}_privacy"
                touch "${base_dir}/${plugin}/${plugin}_privacy.bundle/PrivacyInfo.xcprivacy"
              done
            done
            
            # Create directly in app bundle locations
            mkdir -p "build/ios/iphoneos/Runner.app/${plugin}_privacy.bundle"
            touch "build/ios/iphoneos/Runner.app/${plugin}_privacy.bundle/${plugin}_privacy"
            touch "build/ios/iphoneos/Runner.app/${plugin}_privacy.bundle/PrivacyInfo.xcprivacy"
            
            # Create in framework location
            mkdir -p "build/ios/iphoneos/Runner.app/Frameworks/${plugin}.framework/${plugin}_privacy.bundle"
            touch "build/ios/iphoneos/Runner.app/Frameworks/${plugin}.framework/${plugin}_privacy.bundle/${plugin}_privacy"
            touch "build/ios/iphoneos/Runner.app/Frameworks/${plugin}.framework/${plugin}_privacy.bundle/PrivacyInfo.xcprivacy"
            
            # Create in special locations
            for dir in "build" "ios" "ios/Flutter"; do
              mkdir -p "${dir}/${plugin}_privacy.bundle"
              touch "${dir}/${plugin}_privacy.bundle/${plugin}_privacy"
              touch "${dir}/${plugin}_privacy.bundle/PrivacyInfo.xcprivacy"
            done
            
            # Create directly in plugin directory
            mkdir -p "${plugin}_privacy.bundle"
            touch "${plugin}_privacy.bundle/${plugin}_privacy"
            touch "${plugin}_privacy.bundle/PrivacyInfo.xcprivacy"
          done

          echo "Created all privacy bundles for plugins"
          find build -name "*_privacy.bundle" -type d | sort
          find ios -name "*_privacy.bundle" -type d | sort

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod setup
          pod install --repo-update || pod install
      - name: Workaround for video_player privacy
        run: |
          # Create directories for all possible locations
          mkdir -p build/ios/Release-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle
          mkdir -p build/ios/Debug-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/video_player_avfoundation_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/Frameworks/video_player_avfoundation.framework/video_player_avfoundation_privacy.bundle

          # Create the required files in each location
          touch build/ios/Release-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/Release-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/Debug-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/Debug-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/iphoneos/Runner.app/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/Frameworks/video_player_avfoundation.framework/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/iphoneos/Runner.app/Frameworks/video_player_avfoundation.framework/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy

          # Create special directory that might be referenced directly
          mkdir -p build/video_player_avfoundation_privacy.bundle
          touch build/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy

          # Add similar fixes for url_launcher_ios
          mkdir -p build/ios/Release-iphoneos/url_launcher_ios/url_launcher_ios_privacy.bundle
          mkdir -p build/ios/Debug-iphoneos/url_launcher_ios/url_launcher_ios_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/url_launcher_ios_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios_privacy.bundle

          touch build/ios/Release-iphoneos/url_launcher_ios/url_launcher_ios_privacy.bundle/url_launcher_ios_privacy
          touch build/ios/Release-iphoneos/url_launcher_ios/url_launcher_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/Debug-iphoneos/url_launcher_ios/url_launcher_ios_privacy.bundle/url_launcher_ios_privacy
          touch build/ios/Debug-iphoneos/url_launcher_ios/url_launcher_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/url_launcher_ios_privacy.bundle/url_launcher_ios_privacy
          touch build/ios/iphoneos/Runner.app/url_launcher_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios_privacy.bundle/url_launcher_ios_privacy
          touch build/ios/iphoneos/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios_privacy.bundle/PrivacyInfo.xcprivacy

          # Create special directory for url_launcher_ios
          mkdir -p build/url_launcher_ios_privacy.bundle
          touch build/url_launcher_ios_privacy.bundle/url_launcher_ios_privacy
          touch build/url_launcher_ios_privacy.bundle/PrivacyInfo.xcprivacy

          # Add similar fixes for sqflite_darwin
          mkdir -p build/ios/Release-iphoneos/sqflite_darwin/sqflite_darwin_privacy.bundle
          mkdir -p build/ios/Debug-iphoneos/sqflite_darwin/sqflite_darwin_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/sqflite_darwin_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/Frameworks/sqflite_darwin.framework/sqflite_darwin_privacy.bundle

          touch build/ios/Release-iphoneos/sqflite_darwin/sqflite_darwin_privacy.bundle/sqflite_darwin_privacy
          touch build/ios/Release-iphoneos/sqflite_darwin/sqflite_darwin_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/Debug-iphoneos/sqflite_darwin/sqflite_darwin_privacy.bundle/sqflite_darwin_privacy
          touch build/ios/Debug-iphoneos/sqflite_darwin/sqflite_darwin_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/sqflite_darwin_privacy.bundle/sqflite_darwin_privacy
          touch build/ios/iphoneos/Runner.app/sqflite_darwin_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/Frameworks/sqflite_darwin.framework/sqflite_darwin_privacy.bundle/sqflite_darwin_privacy
          touch build/ios/iphoneos/Runner.app/Frameworks/sqflite_darwin.framework/sqflite_darwin_privacy.bundle/PrivacyInfo.xcprivacy

          # Create special directory for sqflite_darwin
          mkdir -p build/sqflite_darwin_privacy.bundle
          touch build/sqflite_darwin_privacy.bundle/sqflite_darwin_privacy
          touch build/sqflite_darwin_privacy.bundle/PrivacyInfo.xcprivacy

          # Add similar fixes for screen_brightness_ios
          mkdir -p build/ios/Release-iphoneos/screen_brightness_ios/screen_brightness_ios_privacy.bundle
          mkdir -p build/ios/Debug-iphoneos/screen_brightness_ios/screen_brightness_ios_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/screen_brightness_ios_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/Frameworks/screen_brightness_ios.framework/screen_brightness_ios_privacy.bundle

          touch build/ios/Release-iphoneos/screen_brightness_ios/screen_brightness_ios_privacy.bundle/screen_brightness_ios_privacy
          touch build/ios/Release-iphoneos/screen_brightness_ios/screen_brightness_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/Debug-iphoneos/screen_brightness_ios/screen_brightness_ios_privacy.bundle/screen_brightness_ios_privacy
          touch build/ios/Debug-iphoneos/screen_brightness_ios/screen_brightness_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/screen_brightness_ios_privacy.bundle/screen_brightness_ios_privacy
          touch build/ios/iphoneos/Runner.app/screen_brightness_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/Frameworks/screen_brightness_ios.framework/screen_brightness_ios_privacy.bundle/screen_brightness_ios_privacy
          touch build/ios/iphoneos/Runner.app/Frameworks/screen_brightness_ios.framework/screen_brightness_ios_privacy.bundle/PrivacyInfo.xcprivacy

          # Create special directory for screen_brightness_ios
          mkdir -p build/screen_brightness_ios_privacy.bundle
          touch build/screen_brightness_ios_privacy.bundle/screen_brightness_ios_privacy
          touch build/screen_brightness_ios_privacy.bundle/PrivacyInfo.xcprivacy

          # Add similar fixes for pointer_interceptor_ios
          mkdir -p build/ios/Release-iphoneos/pointer_interceptor_ios/pointer_interceptor_ios_privacy.bundle
          mkdir -p build/ios/Debug-iphoneos/pointer_interceptor_ios/pointer_interceptor_ios_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/pointer_interceptor_ios_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/Frameworks/pointer_interceptor_ios.framework/pointer_interceptor_ios_privacy.bundle

          touch build/ios/Release-iphoneos/pointer_interceptor_ios/pointer_interceptor_ios_privacy.bundle/pointer_interceptor_ios_privacy
          touch build/ios/Release-iphoneos/pointer_interceptor_ios/pointer_interceptor_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/Debug-iphoneos/pointer_interceptor_ios/pointer_interceptor_ios_privacy.bundle/pointer_interceptor_ios_privacy
          touch build/ios/Debug-iphoneos/pointer_interceptor_ios/pointer_interceptor_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/pointer_interceptor_ios_privacy.bundle/pointer_interceptor_ios_privacy
          touch build/ios/iphoneos/Runner.app/pointer_interceptor_ios_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/Frameworks/pointer_interceptor_ios.framework/pointer_interceptor_ios_privacy.bundle/pointer_interceptor_ios_privacy
          touch build/ios/iphoneos/Runner.app/Frameworks/pointer_interceptor_ios.framework/pointer_interceptor_ios_privacy.bundle/PrivacyInfo.xcprivacy

          # Create special directory for pointer_interceptor_ios
          mkdir -p build/pointer_interceptor_ios_privacy.bundle
          touch build/pointer_interceptor_ios_privacy.bundle/pointer_interceptor_ios_privacy
          touch build/pointer_interceptor_ios_privacy.bundle/PrivacyInfo.xcprivacy

      - name: Run comprehensive privacy bundle fix script
        run: |
          chmod +x ./privacy_bundle_fix.sh
          ./privacy_bundle_fix.sh

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r app-release.ipa Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/app-release.ipa
