name: Flutter CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"

      - name: Display Flutter/Dart version
        run: |
          flutter --version
          dart --version

      - name: Get dependencies
        run: flutter pub get

      - name: Fix plugin issues
        run: |
          echo "Running plugin fixes"
          # Simplified fix script to avoid complex heredocs
          mkdir -p "$HOME/.pub-cache/hosted/pub.dev/video_thumbnail-0.5.3/android/"
          mkdir -p "$HOME/.pub-cache/hosted/pub.dev/image_gallery_saver-2.0.3/android/"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Pod repo update
        run: pod repo update

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod setup
          pod install --repo-update || pod install
      - name: Workaround for video_player privacy
        run: |
          # Create directories for all possible locations
          mkdir -p build/ios/Release-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle
          mkdir -p build/ios/Debug-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/video_player_avfoundation_privacy.bundle
          mkdir -p build/ios/iphoneos/Runner.app/Frameworks/video_player_avfoundation.framework/video_player_avfoundation_privacy.bundle

          # Create the required files in each location
          touch build/ios/Release-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/Release-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/Debug-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/Debug-iphoneos/video_player_avfoundation/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/iphoneos/Runner.app/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy
          touch build/ios/iphoneos/Runner.app/Frameworks/video_player_avfoundation.framework/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/ios/iphoneos/Runner.app/Frameworks/video_player_avfoundation.framework/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy

          # Create special directory that might be referenced directly
          mkdir -p build/video_player_avfoundation_privacy.bundle
          touch build/video_player_avfoundation_privacy.bundle/video_player_avfoundation_privacy
          touch build/video_player_avfoundation_privacy.bundle/PrivacyInfo.xcprivacy

      - name: Run comprehensive privacy bundle fix script
        run: |
          chmod +x ./privacy_bundle_fix.sh
          ./privacy_bundle_fix.sh

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r app-release.ipa Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/app-release.ipa
