name: iOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Manual trigger

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"

      - name: Install Dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Update xcconfig for iPhone only and no code signing
        run: |
          echo "TARGETED_DEVICE_FAMILY = 1;" >> ios/Flutter/Debug.xcconfig
          echo "CODE_SIGNING_REQUIRED = NO;" >> ios/Flutter/Debug.xcconfig
          echo "CODE_SIGNING_ALLOWED = NO;" >> ios/Flutter/Debug.xcconfig

      - name: Build iOS (no signing)
        run: flutter build ios --no-codesign

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
